### ISSUE TITLE
Review: deploy code to PyPI

### ISSUE THREAD

**Issue by cthoyt** [rs-costa/sbml2hyb#2]
After packing the code in #1, it would be paramount to deploy the code to the Python Package Index (PyPI) such that users can effortlessly install with `pip`

**Comment by cthoyt** [comment]
It seems the code was deployed to the TestPyPI but not the actual PyPI. Test PyPI is not mean to be used in production - ideally only to check the package works. Please deploy to regular PyPI so there is something https://pypi.org/project/sbml2hyb/ and you can do `pip install sbml2hyb`

**Comment by r-costa** [comment]
Done. https://pypi.org/project/sbml2hyb/
